### ISSUE TITLE
Need Update for TWW

### ISSUE THREAD

**Issue by GMably** [Kkthnx-Wow/CharInspectPlus#1]
Hi, i don't know if you notice, but with the new patch there is this lua error, that glitch the addon from working correclty. 

There are three problems that i encountered : 
1st ; The background isn't working,
2nd : The size, is not wide 
3rd : The left weapon, is swap with the right one

I Hope you will fix this as soon as you can, 
Thank

![Wow_Rog0s4RYF6](https://github.com/user-attachments/assets/389506a6-b846-4560-8cad-892e3e44632f)

"
1x ...Ons/BetterCharacter&InspectFrames/CharacterFrame.lua:66: hooksecurefunc(): CharacterFrame_Expand is not a function
[string "=[C]"]: ?
[string "@BetterCharacter&InspectFrames/CharacterFrame.lua"]:66: in function <...Ons/BetterCharacter&InspectFrames/CharacterFrame.lua:35>

Locals:

"

**Comment by Kkthnx** [comment]
Already fixed. Thank you <3
